import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;

public class MalzemeJDialog extends javax.swing.JDialog {

    public MalzemeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadMalzemeler();  // Malzemeleri yükleyip ComboBox'a ekle
        loadMalzemeTable();
    }

    // ComboBox'a malzemeleri ekler
    private void loadMalzemeler() {
        try {
            ResultSet rs = DbHelper.getMalzemeler();
            malzeme_comboBox.removeAllItems();  // ComboBox'ı temizle
            while (rs.next()) {
                malzeme_comboBox.addItem(rs.getString("MalzemeAdi"));  // Malzemeleri ekle
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    // Malzemeler tablosunu veri ile doldurur
    private void loadMalzemeTable() {
        try {
            ResultSet rs = DbHelper.getAllMalzemeler();
            DefaultTableModel model = (DefaultTableModel) malzemeTable.getModel();
            model.setRowCount(0);  // Tabloyu sıfırla

            while (rs.next()) {
                int malzemeID = rs.getInt("MalzemeID");
                String malzemeAdi = rs.getString("MalzemeAdi");
                String toplamMiktar = rs.getString("ToplamMiktar");
                String malzemeBirim = rs.getString("MalzemeBirim");
                double birimFiyat = rs.getDouble("BirimFiyat");

                model.addRow(new Object[]{malzemeID, malzemeAdi, toplamMiktar, malzemeBirim, birimFiyat});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        malzeme_comboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_malzememiktar = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buton_malzemeEkle = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        malzemeEkleTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        malzemeTable = new javax.swing.JTable();
        buton_yeniMalzeme = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        buton_tamamla = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_malzeme = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_toplammiktar = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_birimtur = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_birimfiyat = new javax.swing.JTextPane();
        buton_malzemeCikar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        malzeme_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Malzeme Adı");

        jScrollPane1.setViewportView(txt_malzememiktar);

        jLabel2.setText("Malzeme Miktarı");

        jLabel3.setText("(kilo, litre, adet, demet)");

        buton_malzemeEkle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buton_malzemeEkle.setText("Malzemeyi Tarife Ekle");
        buton_malzemeEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_malzemeEkleActionPerformed(evt);
            }
        });

        malzemeEkleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Malzeme Adı", "Malzeme Miktarı"
            }
        ));
        jScrollPane2.setViewportView(malzemeEkleTable);

        malzemeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Malzeme ID", "Malzeme Adı", "Toplam Miktar", "Birimi Türü", "Birim Fiyatı"
            }
        ));
        malzemeTable.setShowGrid(true);
        jScrollPane3.setViewportView(malzemeTable);

        buton_yeniMalzeme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buton_yeniMalzeme.setText("Yeni Malzeme Ekle");
        buton_yeniMalzeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_yeniMalzemeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("YENİ MALZEME EKLE");

        buton_tamamla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buton_tamamla.setText("Tarif Eklemeyi Tamamla");
        buton_tamamla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_tamamlaActionPerformed(evt);
            }
        });

        jLabel5.setText("Malzeme Adı");

        jLabel6.setText("Toplam Miktar");

        jScrollPane5.setViewportView(txt_malzeme);

        jScrollPane4.setViewportView(txt_toplammiktar);

        jLabel7.setText("Birim Türü");

        jScrollPane6.setViewportView(txt_birimtur);

        jLabel8.setText("Birim Fiyatı");

        jScrollPane7.setViewportView(txt_birimfiyat);

        buton_malzemeCikar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buton_malzemeCikar.setText("Malzemeyi Tariften Çıkar");
        buton_malzemeCikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_malzemeCikarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(buton_yeniMalzeme, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(malzeme_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buton_malzemeEkle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buton_malzemeCikar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buton_tamamla)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addComponent(buton_yeniMalzeme)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(malzeme_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buton_malzemeEkle)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(buton_tamamla)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buton_malzemeCikar)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton_malzemeEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_malzemeEkleActionPerformed
        // Seçilen malzeme adı ve miktarı al
        String malzemeAdi = (String) malzeme_comboBox.getSelectedItem();
        String malzemeMiktar = txt_malzememiktar.getText();

        // Eğer miktar boşsa uyarı göster
        if (malzemeAdi.isEmpty() || malzemeMiktar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen bir malzeme ve miktar girin!", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Malzemenin tabloya daha önce eklenip eklenmediğini kontrol et
        DefaultTableModel model = (DefaultTableModel) malzemeEkleTable.getModel();
        boolean malzemeVar = false;

        for (int i = 0; i < model.getRowCount(); i++) {
            String mevcutMalzemeAdi = (String) model.getValueAt(i, 0);
            if (mevcutMalzemeAdi.equals(malzemeAdi)) {
                malzemeVar = true;
                break;
            }
        }

        // Eğer malzeme zaten eklenmişse uyarı göster
        if (malzemeVar) {
            JOptionPane.showMessageDialog(this, "Bu malzeme zaten tarifte mevcut!", "Hata", JOptionPane.ERROR_MESSAGE);
        } else {
            // Malzeme ve miktarı tabloya ekle
            model.addRow(new Object[]{malzemeAdi, malzemeMiktar});

            // Text alanını temizle
            txt_malzememiktar.setText("");
        }
    }//GEN-LAST:event_buton_malzemeEkleActionPerformed

    private void buton_tamamlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_tamamlaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buton_tamamlaActionPerformed

    private void buton_malzemeCikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_malzemeCikarActionPerformed
        // Tablo üzerinde seçili olan satırı al
        int selectedRow = malzemeEkleTable.getSelectedRow();

        // Eğer bir satır seçili değilse uyarı göster
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Lütfen çıkarmak istediğiniz malzemeyi seçin!", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Seçili satırı tablodan çıkar
        DefaultTableModel model = (DefaultTableModel) malzemeEkleTable.getModel();
        model.removeRow(selectedRow);

        JOptionPane.showMessageDialog(this, "Malzeme tariften çıkarıldı.", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buton_malzemeCikarActionPerformed

    private void buton_yeniMalzemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_yeniMalzemeActionPerformed
        // Text alanlarından bilgileri al
        String malzemeAdi = txt_malzeme.getText();
        String toplamMiktar = txt_toplammiktar.getText();
        String malzemeBirim = txt_birimtur.getText();
        String birimFiyatStr = txt_birimfiyat.getText();

        // Eğer bir alan boşsa uyarı göster
        if (malzemeAdi.isEmpty() || toplamMiktar.isEmpty() || malzemeBirim.isEmpty() || birimFiyatStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lütfen tüm alanları doldurun!", "Hata", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Birim fiyatını double'a çevir
            double birimFiyat = Double.parseDouble(birimFiyatStr);

            // Yeni malzemeyi veri tabanına ekle
            DbHelper.insertMalzeme(malzemeAdi, toplamMiktar, malzemeBirim, birimFiyat);

            // Başarılı mesajı göster
            JOptionPane.showMessageDialog(this, "Malzeme başarıyla eklendi.", "Başarılı", JOptionPane.INFORMATION_MESSAGE);

            // Text alanlarını temizle
            txt_malzeme.setText("");
            txt_toplammiktar.setText("");
            txt_birimtur.setText("");
            txt_birimfiyat.setText("");

            // Malzemeler tablosunu güncelle
            loadMalzemeTable();

        } catch (NumberFormatException e) {
            // Eğer birim fiyatı geçerli bir sayı değilse uyarı göster
            JOptionPane.showMessageDialog(this, "Birim fiyatı geçerli bir sayı olmalıdır!", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buton_yeniMalzemeActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MalzemeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MalzemeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MalzemeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MalzemeJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MalzemeJDialog dialog = new MalzemeJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton_malzemeCikar;
    private javax.swing.JButton buton_malzemeEkle;
    private javax.swing.JButton buton_tamamla;
    private javax.swing.JButton buton_yeniMalzeme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable malzemeEkleTable;
    private javax.swing.JTable malzemeTable;
    private javax.swing.JComboBox<String> malzeme_comboBox;
    private javax.swing.JTextPane txt_birimfiyat;
    private javax.swing.JTextPane txt_birimtur;
    private javax.swing.JTextPane txt_malzeme;
    private javax.swing.JTextPane txt_malzememiktar;
    private javax.swing.JTextPane txt_toplammiktar;
    // End of variables declaration//GEN-END:variables
}
